### ISSUE TITLE
Network Error on log in

### ISSUE THREAD

**Issue by euch** [bosha/vkaudiodump#1]
Hello,

I'm getting this error

```
./vkAudioDump --email 'my@email.com' --password 'password' --notreally
Authorizing on vk.com ..
No previous authorization found ..
Network error: vk.com not available. Check your internet connection

```

What is the possible reason? Is it possible to solve it?
Thanks in advance!

**Comment by bosha** [comment]
Hi!

Do you behind NAT, or Firewall? Probably 80 (or 463 if you specified in vk.com settings) blocked?

**Comment by KarelWintersky** [comment]
Same error.
No NAT, No firewall blocked.

**Comment by bosha** [comment]
It's quite a lot has been changed since 2015. VK currently does not allow directly download music files so this script pretty much unusable.

**Comment by KarelWintersky** [comment]
Please, archive repo
